# Generated by Django 4.2.11 on 2024-03-20 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loan_loan_annuity_payment_loan_loan_srok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
